### PR TITLE
Fix generic

### PR DESCRIPTION
**Pull request by karlhorky**
Fixes implementation of #31

### CODE REVIEW

**Comment by bendrucker** [comment]
Can you add a failing test case that passes with your changes? I don't write TypeScript and rely on test coverage for details like this.

**Comment by karlhorky** [comment]
Sure! Can you enable the tests for branches as well? So I can see whether they pass here?

**Comment by karlhorky** [comment]
Ah actually, it seems like the tests are actually wrong, so I can just fix them :)

**Comment by karlhorky** [comment]
One thing that I would like to do (just as a fun project) is to add proper recursive types using the new Template Literal Types in TypeScript 4.1.2.

There is a `ToSnakeCase` type by @mmkal here:

https://github.com/microsoft/TypeScript/pull/40336#issuecomment-686541786

So then TypeScript would know exactly what properties are on the final object.

**Comment by karlhorky** [comment]
@bendrucker tests and types are fixed (in [`1bab44b`](https://github.com/bendrucker/snakecase-keys/pull/41/commits/1bab44b3f11a969829753f7641206264fa7b3b0f))

**Comment by bendrucker** [comment]
Great work, thank you!

**Comment by karlhorky** [comment]
Glad to help, thanks for the merge!

**Pull request merged**
